[docker]
configs = [
    "selenium/standalone-firefox:4.0.0-beta-3-prerelease-20210321", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210321", "{\"browserName\": \"chrome\"}"
 ]
url = "http://host.docker.internal:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20210315"
