[docker]
configs = [
    "localhost:5000/selenium/standalone-firefox:4.0.0-beta-4-prerelease-20210527", "{\"browserName\": \"firefox\"}",
    "localhost:5000/selenium/standalone-chrome:4.0.0-beta-4-prerelease-20210527", "{\"browserName\": \"chrome\"}"
 ]
url = "http://host.docker.internal:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20210315"
